import type { Config } from "./config.js";

const TOKEN_PATH = "/get_access_token";

// The access token lives 24h. It is replaced this long before it expires, so
// it never lapses between being read here and being checked by the API.
const EXPIRY_MARGIN_MS = 5 * 60 * 1000;

// The API's Lambdas time out at 30s, so waiting any longer gains nothing.
const REQUEST_TIMEOUT_MS = 30 * 1000;

// Every reply from the API, success or error, is {status, message}. Replies
// generated by API Gateway itself (authorizer denials, throttling) carry only
// {message}.
export type ApiEnvelope = {
  status?: string;
  message?: any;
};

type ApiReply = {
  httpStatus: number;
  payload: ApiEnvelope | undefined;
};

export type ApiClient = {
  get(path: string, query?: Record<string, string>): Promise<ApiEnvelope>;
  post(path: string, body: unknown): Promise<ApiEnvelope>;
};

export function createApiClient(config: Config): ApiClient {
  let accessToken: string | undefined;
  let expiresAt = 0;
  let pendingToken: Promise<string> | undefined;

  async function send(
    method: "GET" | "POST",
    path: string,
    bearer: string,
    query?: Record<string, string>,
    body?: unknown
  ): Promise<ApiReply> {
    const url = new URL(config.baseUrl + path);
    for (const [name, value] of Object.entries(query ?? {})) {
      url.searchParams.set(name, value);
    }

    let res: Response;
    try {
      res = await fetch(url, {
        method,
        headers: {
          "x-api-key": config.apiKey,
          Authorization: `Bearer ${bearer}`,
          ...(body === undefined ? {} : { "Content-Type": "application/json" }),
        },
        body: body === undefined ? undefined : JSON.stringify(body),
        signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
      });
    } catch (e) {
      throw new Error(`Could not reach the Atomberg API at ${config.baseUrl}: ${e instanceof Error ? e.message : e}`);
    }

    const text = await res.text();
    let payload: ApiEnvelope | undefined;
    try {
      payload = text ? JSON.parse(text) : undefined;
    } catch {
      payload = { message: text };
    }
    return { httpStatus: res.status, payload };
  }

  async function fetchAccessToken(): Promise<string> {
    const reply = await send("GET", TOKEN_PATH, config.refreshToken);
    const token = reply.payload?.message?.access_token;
    if (!isSuccess(reply) || typeof token !== "string") {
      throw toError(TOKEN_PATH, reply);
    }
    accessToken = token;
    expiresAt = readExpiry(token);
    return token;
  }

  // Every request, get_access_token included, spends one from the API key's
  // daily quota, so concurrent tool calls share a single refresh.
  function getAccessToken(): Promise<string> {
    if (accessToken && Date.now() < expiresAt - EXPIRY_MARGIN_MS) {
      return Promise.resolve(accessToken);
    }
    pendingToken ??= fetchAccessToken().finally(() => {
      pendingToken = undefined;
    });
    return pendingToken;
  }

  async function call(
    method: "GET" | "POST",
    path: string,
    query?: Record<string, string>,
    body?: unknown
  ): Promise<ApiEnvelope> {
    let reply = await send(method, path, await getAccessToken(), query, body);

    // A token rejected before its exp (the signing key was rotated, say) gets
    // replaced and the request tried exactly once more. Auth is checked before
    // anything is dispatched, so this never repeats a command.
    if (reply.httpStatus === 401) {
      accessToken = undefined;
      reply = await send(method, path, await getAccessToken(), query, body);
    }

    if (!isSuccess(reply)) {
      throw toError(path, reply);
    }
    return reply.payload ?? {};
  }

  return {
    get: (path, query) => call("GET", path, query),
    post: (path, body) => call("POST", path, undefined, body),
  };
}

function isSuccess(reply: ApiReply): boolean {
  return reply.httpStatus >= 200 && reply.httpStatus < 300 && reply.payload?.status !== "Error";
}

// Builds an error whose message the model can act on: the API's own message,
// plus what to do about it where the message alone doesn't say.
function toError(path: string, reply: ApiReply): Error {
  const { httpStatus, payload } = reply;
  const message = typeof payload?.message === "string" && payload.message ? payload.message : "no message";
  const fromGateway = payload?.status === undefined;

  let hint = "";
  if (httpStatus === 429) {
    hint = "The API key's rate limit or daily quota is exhausted. The daily quota resets at 00:00 UTC.";
  } else if (httpStatus === 403 && message === "Missing Authentication Token") {
    // API Gateway's reply for a path it has no route for.
    hint = `No such endpoint at ${path}. Check ATOMBERG_API_BASE_URL.`;
  } else if (httpStatus === 403 && fromGateway) {
    // The authorizer's only Deny is for an exhausted quota; a bad key is a 401.
    hint = "The gateway denied the request, which means the API key's daily quota is used up. It resets at 00:00 UTC.";
  } else if (httpStatus === 401 && path === TOKEN_PATH) {
    hint =
      "The API key or refresh token was rejected. Generate new ones from Developer Mode in the Atomberg Home app " +
      "and update ATOMBERG_API_KEY and ATOMBERG_REFRESH_TOKEN in the MCP client config.";
  }

  return new Error(`${path} failed with HTTP ${httpStatus}: ${message}${hint ? `\n${hint}` : ""}`);
}

// The access token is a JWT whose exp claim says when to replace it. If that
// can't be read, assume the documented 24h and let a 401 correct it.
function readExpiry(token: string): number {
  try {
    const claims = JSON.parse(Buffer.from(token.split(".")[1], "base64url").toString("utf8"));
    if (typeof claims.exp === "number") {
      return claims.exp * 1000;
    }
  } catch {
    // fall through
  }
  return Date.now() + 24 * 60 * 60 * 1000;
}
