// Everything comes from the environment the MCP client launches the server
// with (the "env" block of its config), so no credential lives in this package.

export const PRODUCTION_BASE_URL = "https://api.developer.atomberg-iot.com/v1";

export type Config = {
  apiKey: string;
  refreshToken: string;
  baseUrl: string;
};

export function loadConfig(env: NodeJS.ProcessEnv = process.env): Config {
  const apiKey = env.ATOMBERG_API_KEY?.trim();
  const refreshToken = env.ATOMBERG_REFRESH_TOKEN?.trim();

  if (!apiKey || !refreshToken) {
    const missing = [!apiKey && "ATOMBERG_API_KEY", !refreshToken && "ATOMBERG_REFRESH_TOKEN"].filter(Boolean);
    throw new Error(
      `Missing ${missing.join(" and ")}. Both are generated by enabling Developer Mode in the Atomberg Home app.`
    );
  }

  return {
    apiKey,
    refreshToken,
    baseUrl: (env.ATOMBERG_API_BASE_URL?.trim() || PRODUCTION_BASE_URL).replace(/\/+$/, ""),
  };
}
